relative_links:
  enabled:     true
  collections: true
  exclude:
    - README.md

highlighter: rouge

tipue_search:
  include:
    pages: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - github-pages
