name: Blackboard Developer Blog
description: The Blackboard Developer Blog is geared towards keeping our Developer Community informed of important changes, notifications, and cool stuff we are working on.
url: https://docs.blackboard.com

relative_links:
  enabled:     true
  collections: true
  exclude:
    - README.md

highlighter: rouge

tipue_search:
  include:
    pages: true

collections:
  authors:
    output: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - github-pages
  - jekyll-analytics
  - jemoji

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-173992978-1
